//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.capec.capec_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;group ref="{http://capec.mitre.org/capec-2}Structured_Text_Group"/>
 *         &lt;element ref="{http://capec.mitre.org/capec-2}Block"/>
 *       &lt;/choice>
 *       &lt;attribute name="Block_Nature">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;enumeration value="Good_Code"/>
 *             &lt;enumeration value="Bad_Code"/>
 *             &lt;enumeration value="Mitigation_Code"/>
 *             &lt;enumeration value="Attack"/>
 *             &lt;enumeration value="Result"/>
 *             &lt;enumeration value="List"/>
 *             &lt;enumeration value="Numeric_List"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textTitleOrTextOrCodeExampleLanguage"
})
@XmlRootElement(name = "Block")
public class Block {

    @XmlElementRefs({
        @XmlElementRef(name = "Images", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Comment", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text_Title", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Block", namespace = "http://capec.mitre.org/capec-2", type = Block.class, required = false),
        @XmlElementRef(name = "Code", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Code_Example_Language", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class, required = false)
    })
    protected List<Object> textTitleOrTextOrCodeExampleLanguage;
    @XmlAttribute(name = "Block_Nature")
    protected String blockNature;

    /**
     * Gets the value of the textTitleOrTextOrCodeExampleLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textTitleOrTextOrCodeExampleLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextTitleOrTextOrCodeExampleLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Block.Images }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Block }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getTextTitleOrTextOrCodeExampleLanguage() {
        if (textTitleOrTextOrCodeExampleLanguage == null) {
            textTitleOrTextOrCodeExampleLanguage = new ArrayList<Object>();
        }
        return this.textTitleOrTextOrCodeExampleLanguage;
    }

    /**
     * Gets the value of the blockNature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockNature() {
        return blockNature;
    }

    /**
     * Sets the value of the blockNature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockNature(String value) {
        this.blockNature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Image" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="Image_Location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Image_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "image"
    })
    public static class Images {

        @XmlElement(name = "Image", required = true)
        protected List<Block.Images.Image> image;

        /**
         * Gets the value of the image property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the image property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Block.Images.Image }
         * 
         * 
         */
        public List<Block.Images.Image> getImage() {
            if (image == null) {
                image = new ArrayList<Block.Images.Image>();
            }
            return this.image;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="Image_Location" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Image_Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imageLocationAndImageTitle"
        })
        public static class Image {

            @XmlElementRefs({
                @XmlElementRef(name = "Image_Title", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class),
                @XmlElementRef(name = "Image_Location", namespace = "http://capec.mitre.org/capec-2", type = JAXBElement.class)
            })
            protected List<JAXBElement<String>> imageLocationAndImageTitle;

            /**
             * Gets the value of the imageLocationAndImageTitle property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the imageLocationAndImageTitle property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getImageLocationAndImageTitle().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * 
             * 
             */
            public List<JAXBElement<String>> getImageLocationAndImageTitle() {
                if (imageLocationAndImageTitle == null) {
                    imageLocationAndImageTitle = new ArrayList<JAXBElement<String>>();
                }
                return this.imageLocationAndImageTitle;
            }

        }

    }

}
