//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * The BaseCollectionType is the base type for other MAEC collection types.
 * 
 * <p>Java class for BaseCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Affinity_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affinity_Degree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseCollectionType", propOrder = {
    "affinityType",
    "affinityDegree",
    "description"
})
@XmlSeeAlso({
    CandidateIndicatorCollectionType.class,
    BehaviorCollectionType.class,
    ObjectCollectionType.class,
    ActionCollectionType.class
})
public class BaseCollectionType {

    @XmlElement(name = "Affinity_Type")
    protected String affinityType;
    @XmlElement(name = "Affinity_Degree")
    protected String affinityDegree;
    @XmlElement(name = "Description")
    protected String description;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the affinityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffinityType() {
        return affinityType;
    }

    /**
     * Sets the value of the affinityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffinityType(String value) {
        this.affinityType = value;
    }

    /**
     * Gets the value of the affinityDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffinityDegree() {
        return affinityDegree;
    }

    /**
     * Sets the value of the affinityDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffinityDegree(String value) {
        this.affinityDegree = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
