//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.default_vocabularies_2.ActionRelationshipTypeEnum10;


/**
 * The BehaviorRelationshipType provides a method for the characterization of relationships between Behaviors. 
 * 
 * <p>Java class for BehaviorRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BehaviorRelationshipType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Behavior_Reference" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}BehaviorReferenceType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://cybox.mitre.org/default_vocabularies-2}ActionRelationshipTypeEnum-1.0">
 *             &lt;enumeration value="Preceded_By"/>
 *             &lt;enumeration value="Followed_By"/>
 *             &lt;enumeration value="Related_To"/>
 *             &lt;enumeration value="Dependent_On"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BehaviorRelationshipType", propOrder = {
    "behaviorReference"
})
public class BehaviorRelationshipType {

    @XmlElement(name = "Behavior_Reference", required = true)
    protected List<BehaviorReferenceType> behaviorReference;
    @XmlAttribute(name = "type")
    protected ActionRelationshipTypeEnum10 type;

    /**
     * Gets the value of the behaviorReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the behaviorReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBehaviorReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BehaviorReferenceType }
     * 
     * 
     */
    public List<BehaviorReferenceType> getBehaviorReference() {
        if (behaviorReference == null) {
            behaviorReference = new ArrayList<BehaviorReferenceType>();
        }
        return this.behaviorReference;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ActionRelationshipTypeEnum10 }
     *     
     */
    public ActionRelationshipTypeEnum10 getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionRelationshipTypeEnum10 }
     *     
     */
    public void setType(ActionRelationshipTypeEnum10 value) {
        this.type = value;
    }

}
