//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.mitre.cybox.cybox_2.ObjectType;


/**
 * The BundleType serves as the high-level construct which encapsulates all Bundle elements, and represents some characterized analysis data (from any arbitrary set of analyses) for a single malware instance in terms of its MAEC Components (e.g., Behaviors, Actions, Objects, etc.).
 * 
 * <p>Java class for BundleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BundleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Malware_Instance_Object_Attributes" type="{http://cybox.mitre.org/cybox-2}ObjectType" minOccurs="0"/>
 *         &lt;element name="AV_Classifications" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}AVClassificationsType" minOccurs="0"/>
 *         &lt;element name="Process_Tree" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}ProcessTreeType" minOccurs="0"/>
 *         &lt;element name="Capabilities" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}CapabilityListType" minOccurs="0"/>
 *         &lt;element name="Behaviors" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}BehaviorListType" minOccurs="0"/>
 *         &lt;element name="Actions" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}ActionListType" minOccurs="0"/>
 *         &lt;element name="Objects" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}ObjectListType" minOccurs="0"/>
 *         &lt;element name="Candidate_Indicators" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}CandidateIndicatorListType" minOccurs="0"/>
 *         &lt;element name="Collections" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}CollectionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="schema_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="4.1" />
 *       &lt;attribute name="defined_subject" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="content_type" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}BundleContentTypeEnum" />
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BundleType", propOrder = {
    "malwareInstanceObjectAttributes",
    "avClassifications",
    "processTree",
    "capabilities",
    "behaviors",
    "actions",
    "objects",
    "candidateIndicators",
    "collections"
})
public class BundleType {

    @XmlElement(name = "Malware_Instance_Object_Attributes")
    protected ObjectType malwareInstanceObjectAttributes;
    @XmlElement(name = "AV_Classifications")
    protected AVClassificationsType avClassifications;
    @XmlElement(name = "Process_Tree")
    protected ProcessTreeType processTree;
    @XmlElement(name = "Capabilities")
    protected CapabilityListType capabilities;
    @XmlElement(name = "Behaviors")
    protected BehaviorListType behaviors;
    @XmlElement(name = "Actions")
    protected ActionListType actions;
    @XmlElement(name = "Objects")
    protected ObjectListType objects;
    @XmlElement(name = "Candidate_Indicators")
    protected CandidateIndicatorListType candidateIndicators;
    @XmlElement(name = "Collections")
    protected CollectionsType collections;
    @XmlAttribute(name = "id", required = true)
    protected QName id;
    @XmlAttribute(name = "schema_version", required = true)
    protected String schemaVersion;
    @XmlAttribute(name = "defined_subject", required = true)
    protected boolean definedSubject;
    @XmlAttribute(name = "content_type")
    protected BundleContentTypeEnum contentType;
    @XmlAttribute(name = "timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the malwareInstanceObjectAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectType }
     *     
     */
    public ObjectType getMalwareInstanceObjectAttributes() {
        return malwareInstanceObjectAttributes;
    }

    /**
     * Sets the value of the malwareInstanceObjectAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectType }
     *     
     */
    public void setMalwareInstanceObjectAttributes(ObjectType value) {
        this.malwareInstanceObjectAttributes = value;
    }

    /**
     * Gets the value of the avClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link AVClassificationsType }
     *     
     */
    public AVClassificationsType getAVClassifications() {
        return avClassifications;
    }

    /**
     * Sets the value of the avClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link AVClassificationsType }
     *     
     */
    public void setAVClassifications(AVClassificationsType value) {
        this.avClassifications = value;
    }

    /**
     * Gets the value of the processTree property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessTreeType }
     *     
     */
    public ProcessTreeType getProcessTree() {
        return processTree;
    }

    /**
     * Sets the value of the processTree property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessTreeType }
     *     
     */
    public void setProcessTree(ProcessTreeType value) {
        this.processTree = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilityListType }
     *     
     */
    public CapabilityListType getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilityListType }
     *     
     */
    public void setCapabilities(CapabilityListType value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the behaviors property.
     * 
     * @return
     *     possible object is
     *     {@link BehaviorListType }
     *     
     */
    public BehaviorListType getBehaviors() {
        return behaviors;
    }

    /**
     * Sets the value of the behaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehaviorListType }
     *     
     */
    public void setBehaviors(BehaviorListType value) {
        this.behaviors = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * @return
     *     possible object is
     *     {@link ActionListType }
     *     
     */
    public ActionListType getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionListType }
     *     
     */
    public void setActions(ActionListType value) {
        this.actions = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectListType }
     *     
     */
    public ObjectListType getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectListType }
     *     
     */
    public void setObjects(ObjectListType value) {
        this.objects = value;
    }

    /**
     * Gets the value of the candidateIndicators property.
     * 
     * @return
     *     possible object is
     *     {@link CandidateIndicatorListType }
     *     
     */
    public CandidateIndicatorListType getCandidateIndicators() {
        return candidateIndicators;
    }

    /**
     * Sets the value of the candidateIndicators property.
     * 
     * @param value
     *     allowed object is
     *     {@link CandidateIndicatorListType }
     *     
     */
    public void setCandidateIndicators(CandidateIndicatorListType value) {
        this.candidateIndicators = value;
    }

    /**
     * Gets the value of the collections property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionsType }
     *     
     */
    public CollectionsType getCollections() {
        return collections;
    }

    /**
     * Sets the value of the collections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionsType }
     *     
     */
    public void setCollections(CollectionsType value) {
        this.collections = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setId(QName value) {
        this.id = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "4.1";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the definedSubject property.
     * 
     */
    public boolean isDefinedSubject() {
        return definedSubject;
    }

    /**
     * Sets the value of the definedSubject property.
     * 
     */
    public void setDefinedSubject(boolean value) {
        this.definedSubject = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link BundleContentTypeEnum }
     *     
     */
    public BundleContentTypeEnum getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundleContentTypeEnum }
     *     
     */
    public void setContentType(BundleContentTypeEnum value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
