//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.cybox_2.ActionReferenceType;
import org.mitre.cybox.cybox_2.OperatorTypeEnum;


/**
 * The CandidateIndicatorCompositionType captures the composition of a Candidate Indicator, via references to any corresponding MAEC entities contained in the Bundle.
 * 
 * <p>Java class for CandidateIndicatorCompositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CandidateIndicatorCompositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="Behavior_Reference" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}BehaviorReferenceType" minOccurs="0"/>
 *           &lt;element name="Action_Reference" type="{http://cybox.mitre.org/cybox-2}ActionReferenceType" minOccurs="0"/>
 *           &lt;element name="Object_Reference" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}ObjectReferenceType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="Sub_Composition" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}CandidateIndicatorCompositionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operator" type="{http://cybox.mitre.org/cybox-2}OperatorTypeEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CandidateIndicatorCompositionType", propOrder = {
    "behaviorReferenceOrActionReferenceOrObjectReference",
    "subComposition"
})
public class CandidateIndicatorCompositionType {

    @XmlElements({
        @XmlElement(name = "Behavior_Reference", type = BehaviorReferenceType.class),
        @XmlElement(name = "Action_Reference", type = ActionReferenceType.class),
        @XmlElement(name = "Object_Reference", type = ObjectReferenceType.class)
    })
    protected List<Object> behaviorReferenceOrActionReferenceOrObjectReference;
    @XmlElement(name = "Sub_Composition")
    protected List<CandidateIndicatorCompositionType> subComposition;
    @XmlAttribute(name = "operator")
    protected OperatorTypeEnum operator;

    /**
     * Gets the value of the behaviorReferenceOrActionReferenceOrObjectReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the behaviorReferenceOrActionReferenceOrObjectReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBehaviorReferenceOrActionReferenceOrObjectReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BehaviorReferenceType }
     * {@link ActionReferenceType }
     * {@link ObjectReferenceType }
     * 
     * 
     */
    public List<Object> getBehaviorReferenceOrActionReferenceOrObjectReference() {
        if (behaviorReferenceOrActionReferenceOrObjectReference == null) {
            behaviorReferenceOrActionReferenceOrObjectReference = new ArrayList<Object>();
        }
        return this.behaviorReferenceOrActionReferenceOrObjectReference;
    }

    /**
     * Gets the value of the subComposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subComposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubComposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CandidateIndicatorCompositionType }
     * 
     * 
     */
    public List<CandidateIndicatorCompositionType> getSubComposition() {
        if (subComposition == null) {
            subComposition = new ArrayList<CandidateIndicatorCompositionType>();
        }
        return this.subComposition;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorTypeEnum }
     *     
     */
    public OperatorTypeEnum getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorTypeEnum }
     *     
     */
    public void setOperator(OperatorTypeEnum value) {
        this.operator = value;
    }

}
