//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mitre.maec.xmlschema.maec_bundle_4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Behavior_QNAME = new QName("http://maec.mitre.org/XMLSchema/maec-bundle-4", "Behavior");
    private final static QName _Action_QNAME = new QName("http://maec.mitre.org/XMLSchema/maec-bundle-4", "Action");
    private final static QName _MAECBundle_QNAME = new QName("http://maec.mitre.org/XMLSchema/maec-bundle-4", "MAEC_Bundle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mitre.maec.xmlschema.maec_bundle_4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BehaviorType }
     * 
     */
    public BehaviorType createBehaviorType() {
        return new BehaviorType();
    }

    /**
     * Create an instance of {@link MalwareActionType }
     * 
     */
    public MalwareActionType createMalwareActionType() {
        return new MalwareActionType();
    }

    /**
     * Create an instance of {@link BundleType }
     * 
     */
    public BundleType createBundleType() {
        return new BundleType();
    }

    /**
     * Create an instance of {@link BehaviorRelationshipListType }
     * 
     */
    public BehaviorRelationshipListType createBehaviorRelationshipListType() {
        return new BehaviorRelationshipListType();
    }

    /**
     * Create an instance of {@link ProcessTreeNodeType }
     * 
     */
    public ProcessTreeNodeType createProcessTreeNodeType() {
        return new ProcessTreeNodeType();
    }

    /**
     * Create an instance of {@link ObjectCollectionListType }
     * 
     */
    public ObjectCollectionListType createObjectCollectionListType() {
        return new ObjectCollectionListType();
    }

    /**
     * Create an instance of {@link BundleReferenceType }
     * 
     */
    public BundleReferenceType createBundleReferenceType() {
        return new BundleReferenceType();
    }

    /**
     * Create an instance of {@link AssociatedCodeType }
     * 
     */
    public AssociatedCodeType createAssociatedCodeType() {
        return new AssociatedCodeType();
    }

    /**
     * Create an instance of {@link CandidateIndicatorCollectionType }
     * 
     */
    public CandidateIndicatorCollectionType createCandidateIndicatorCollectionType() {
        return new CandidateIndicatorCollectionType();
    }

    /**
     * Create an instance of {@link ActionImplementationType }
     * 
     */
    public ActionImplementationType createActionImplementationType() {
        return new ActionImplementationType();
    }

    /**
     * Create an instance of {@link CapabilityRelationshipType }
     * 
     */
    public CapabilityRelationshipType createCapabilityRelationshipType() {
        return new CapabilityRelationshipType();
    }

    /**
     * Create an instance of {@link ExploitType }
     * 
     */
    public ExploitType createExploitType() {
        return new ExploitType();
    }

    /**
     * Create an instance of {@link ObjectReferenceType }
     * 
     */
    public ObjectReferenceType createObjectReferenceType() {
        return new ObjectReferenceType();
    }

    /**
     * Create an instance of {@link BehaviorCollectionType }
     * 
     */
    public BehaviorCollectionType createBehaviorCollectionType() {
        return new BehaviorCollectionType();
    }

    /**
     * Create an instance of {@link BehavioralActionsType }
     * 
     */
    public BehavioralActionsType createBehavioralActionsType() {
        return new BehavioralActionsType();
    }

    /**
     * Create an instance of {@link ObjectReferenceListType }
     * 
     */
    public ObjectReferenceListType createObjectReferenceListType() {
        return new ObjectReferenceListType();
    }

    /**
     * Create an instance of {@link MalwareEntityType }
     * 
     */
    public MalwareEntityType createMalwareEntityType() {
        return new MalwareEntityType();
    }

    /**
     * Create an instance of {@link CapabilityType }
     * 
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link BehaviorReferenceType }
     * 
     */
    public BehaviorReferenceType createBehaviorReferenceType() {
        return new BehaviorReferenceType();
    }

    /**
     * Create an instance of {@link BehavioralActionEquivalenceReferenceType }
     * 
     */
    public BehavioralActionEquivalenceReferenceType createBehavioralActionEquivalenceReferenceType() {
        return new BehavioralActionEquivalenceReferenceType();
    }

    /**
     * Create an instance of {@link CapabilityPropertyType }
     * 
     */
    public CapabilityPropertyType createCapabilityPropertyType() {
        return new CapabilityPropertyType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ActionCollectionListType }
     * 
     */
    public ActionCollectionListType createActionCollectionListType() {
        return new ActionCollectionListType();
    }

    /**
     * Create an instance of {@link ObjectCollectionType }
     * 
     */
    public ObjectCollectionType createObjectCollectionType() {
        return new ObjectCollectionType();
    }

    /**
     * Create an instance of {@link BaseCollectionType }
     * 
     */
    public BaseCollectionType createBaseCollectionType() {
        return new BaseCollectionType();
    }

    /**
     * Create an instance of {@link AVClassificationsType }
     * 
     */
    public AVClassificationsType createAVClassificationsType() {
        return new AVClassificationsType();
    }

    /**
     * Create an instance of {@link CapabilityReferenceType }
     * 
     */
    public CapabilityReferenceType createCapabilityReferenceType() {
        return new CapabilityReferenceType();
    }

    /**
     * Create an instance of {@link APICallType }
     * 
     */
    public APICallType createAPICallType() {
        return new APICallType();
    }

    /**
     * Create an instance of {@link BehaviorReferenceListType }
     * 
     */
    public BehaviorReferenceListType createBehaviorReferenceListType() {
        return new BehaviorReferenceListType();
    }

    /**
     * Create an instance of {@link CapabilityObjectiveRelationshipType }
     * 
     */
    public CapabilityObjectiveRelationshipType createCapabilityObjectiveRelationshipType() {
        return new CapabilityObjectiveRelationshipType();
    }

    /**
     * Create an instance of {@link CapabilityListType }
     * 
     */
    public CapabilityListType createCapabilityListType() {
        return new CapabilityListType();
    }

    /**
     * Create an instance of {@link BehaviorRelationshipType }
     * 
     */
    public BehaviorRelationshipType createBehaviorRelationshipType() {
        return new BehaviorRelationshipType();
    }

    /**
     * Create an instance of {@link ObjectListType }
     * 
     */
    public ObjectListType createObjectListType() {
        return new ObjectListType();
    }

    /**
     * Create an instance of {@link BehavioralActionType }
     * 
     */
    public BehavioralActionType createBehavioralActionType() {
        return new BehavioralActionType();
    }

    /**
     * Create an instance of {@link BehaviorCollectionListType }
     * 
     */
    public BehaviorCollectionListType createBehaviorCollectionListType() {
        return new BehaviorCollectionListType();
    }

    /**
     * Create an instance of {@link ActionReferenceListType }
     * 
     */
    public ActionReferenceListType createActionReferenceListType() {
        return new ActionReferenceListType();
    }

    /**
     * Create an instance of {@link CandidateIndicatorListType }
     * 
     */
    public CandidateIndicatorListType createCandidateIndicatorListType() {
        return new CandidateIndicatorListType();
    }

    /**
     * Create an instance of {@link BehaviorPurposeType }
     * 
     */
    public BehaviorPurposeType createBehaviorPurposeType() {
        return new BehaviorPurposeType();
    }

    /**
     * Create an instance of {@link ProcessTreeType }
     * 
     */
    public ProcessTreeType createProcessTreeType() {
        return new ProcessTreeType();
    }

    /**
     * Create an instance of {@link CandidateIndicatorCollectionListType }
     * 
     */
    public CandidateIndicatorCollectionListType createCandidateIndicatorCollectionListType() {
        return new CandidateIndicatorCollectionListType();
    }

    /**
     * Create an instance of {@link ActionCollectionType }
     * 
     */
    public ActionCollectionType createActionCollectionType() {
        return new ActionCollectionType();
    }

    /**
     * Create an instance of {@link CandidateIndicatorCompositionType }
     * 
     */
    public CandidateIndicatorCompositionType createCandidateIndicatorCompositionType() {
        return new CandidateIndicatorCompositionType();
    }

    /**
     * Create an instance of {@link CapabilityObjectiveReferenceType }
     * 
     */
    public CapabilityObjectiveReferenceType createCapabilityObjectiveReferenceType() {
        return new CapabilityObjectiveReferenceType();
    }

    /**
     * Create an instance of {@link PlatformListType }
     * 
     */
    public PlatformListType createPlatformListType() {
        return new PlatformListType();
    }

    /**
     * Create an instance of {@link CVEVulnerabilityType }
     * 
     */
    public CVEVulnerabilityType createCVEVulnerabilityType() {
        return new CVEVulnerabilityType();
    }

    /**
     * Create an instance of {@link ActionListType }
     * 
     */
    public ActionListType createActionListType() {
        return new ActionListType();
    }

    /**
     * Create an instance of {@link BehaviorListType }
     * 
     */
    public BehaviorListType createBehaviorListType() {
        return new BehaviorListType();
    }

    /**
     * Create an instance of {@link CollectionsType }
     * 
     */
    public CollectionsType createCollectionsType() {
        return new CollectionsType();
    }

    /**
     * Create an instance of {@link BehavioralActionReferenceType }
     * 
     */
    public BehavioralActionReferenceType createBehavioralActionReferenceType() {
        return new BehavioralActionReferenceType();
    }

    /**
     * Create an instance of {@link AVClassificationType }
     * 
     */
    public AVClassificationType createAVClassificationType() {
        return new AVClassificationType();
    }

    /**
     * Create an instance of {@link CapabilityObjectiveType }
     * 
     */
    public CapabilityObjectiveType createCapabilityObjectiveType() {
        return new CapabilityObjectiveType();
    }

    /**
     * Create an instance of {@link ParameterListType }
     * 
     */
    public ParameterListType createParameterListType() {
        return new ParameterListType();
    }

    /**
     * Create an instance of {@link CandidateIndicatorType }
     * 
     */
    public CandidateIndicatorType createCandidateIndicatorType() {
        return new CandidateIndicatorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BehaviorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maec.mitre.org/XMLSchema/maec-bundle-4", name = "Behavior")
    public JAXBElement<BehaviorType> createBehavior(BehaviorType value) {
        return new JAXBElement<BehaviorType>(_Behavior_QNAME, BehaviorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MalwareActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maec.mitre.org/XMLSchema/maec-bundle-4", name = "Action")
    public JAXBElement<MalwareActionType> createAction(MalwareActionType value) {
        return new JAXBElement<MalwareActionType>(_Action_QNAME, MalwareActionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BundleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maec.mitre.org/XMLSchema/maec-bundle-4", name = "MAEC_Bundle")
    public JAXBElement<BundleType> createMAECBundle(BundleType value) {
        return new JAXBElement<BundleType>(_MAECBundle_QNAME, BundleType.class, null, value);
    }

}
