//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package oasis.names.tc.ciq.xpil._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LanguageSkillsList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LanguageSkillsList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="No"/>
 *     &lt;enumeration value="Fluent"/>
 *     &lt;enumeration value="Excellent"/>
 *     &lt;enumeration value="Good"/>
 *     &lt;enumeration value="Bad"/>
 *     &lt;enumeration value="Average"/>
 *     &lt;enumeration value="Fair"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LanguageSkillsList")
@XmlEnum
public enum LanguageSkillsList {

    @XmlEnumValue("No")
    NO("No"),
    @XmlEnumValue("Fluent")
    FLUENT("Fluent"),
    @XmlEnumValue("Excellent")
    EXCELLENT("Excellent"),
    @XmlEnumValue("Good")
    GOOD("Good"),
    @XmlEnumValue("Bad")
    BAD("Bad"),
    @XmlEnumValue("Average")
    AVERAGE("Average"),
    @XmlEnumValue("Fair")
    FAIR("Fair");
    private final String value;

    LanguageSkillsList(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageSkillsList fromValue(String v) {
        for (LanguageSkillsList c: LanguageSkillsList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
