//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_package_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * The PackageType is the namesake type of the MAEC Package schema, and captures either a single Malware Subject, or a collection of Malware Subjects that are related in some way (even if exact details of the relationship are unknown). Unlike the MAEC Bundle, which captures only the MAEC-characterized analysis results for a malware instance, the Package permits the capture of additional metadata relating to the analysis, relationships between Malware Subjects, and similar types of entities.
 * 
 * <p>Java class for PackageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Malware_Subjects" type="{http://maec.mitre.org/XMLSchema/maec-package-2}MalwareSubjectListType"/>
 *         &lt;element name="Grouping_Relationships" type="{http://maec.mitre.org/XMLSchema/maec-package-2}GroupingRelationshipListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="schema_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2.1" />
 *       &lt;attribute name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageType", propOrder = {
    "malwareSubjects",
    "groupingRelationships"
})
public class PackageType {

    @XmlElement(name = "Malware_Subjects", required = true)
    protected MalwareSubjectListType malwareSubjects;
    @XmlElement(name = "Grouping_Relationships")
    protected GroupingRelationshipListType groupingRelationships;
    @XmlAttribute(name = "id", required = true)
    protected QName id;
    @XmlAttribute(name = "schema_version", required = true)
    protected String schemaVersion;
    @XmlAttribute(name = "timestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the malwareSubjects property.
     * 
     * @return
     *     possible object is
     *     {@link MalwareSubjectListType }
     *     
     */
    public MalwareSubjectListType getMalwareSubjects() {
        return malwareSubjects;
    }

    /**
     * Sets the value of the malwareSubjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link MalwareSubjectListType }
     *     
     */
    public void setMalwareSubjects(MalwareSubjectListType value) {
        this.malwareSubjects = value;
    }

    /**
     * Gets the value of the groupingRelationships property.
     * 
     * @return
     *     possible object is
     *     {@link GroupingRelationshipListType }
     *     
     */
    public GroupingRelationshipListType getGroupingRelationships() {
        return groupingRelationships;
    }

    /**
     * Sets the value of the groupingRelationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupingRelationshipListType }
     *     
     */
    public void setGroupingRelationships(GroupingRelationshipListType value) {
        this.groupingRelationships = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setId(QName value) {
        this.id = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "2.1";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
