//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.icasi.cvrf.schema.common._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferenceTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="External"/>
 *     &lt;enumeration value="Self"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReferenceTypeEnum")
@XmlEnum
public enum ReferenceTypeEnum {


    /**
     * This document is an external reference to the current vulnerability.
     * 
     */
    @XmlEnumValue("External")
    EXTERNAL("External"),

    /**
     * This document is a reference to this same vulnerability.
     * 
     */
    @XmlEnumValue("Self")
    SELF("Self");
    private final String value;

    ReferenceTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferenceTypeEnum fromValue(String v) {
        for (ReferenceTypeEnum c: ReferenceTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
