//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The DHCPServerListType type specifies a list of DHCP Servers, via their IP addresses.
 * 
 * <p>Java class for DHCPServerListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DHCPServerListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DHCP_Server_Address" type="{http://cybox.mitre.org/objects#AddressObject-2}AddressObjectType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DHCPServerListType", namespace = "http://cybox.mitre.org/objects#SystemObject-2", propOrder = {
    "dhcpServerAddress"
})
public class DHCPServerListType {

    @XmlElement(name = "DHCP_Server_Address", required = true)
    protected List<AddressObjectType> dhcpServerAddress;

    /**
     * Gets the value of the dhcpServerAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dhcpServerAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDHCPServerAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressObjectType }
     * 
     * 
     */
    public List<AddressObjectType> getDHCPServerAddress() {
        if (dhcpServerAddress == null) {
            dhcpServerAddress = new ArrayList<AddressObjectType>();
        }
        return this.dhcpServerAddress;
    }

}
