//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.icasi.cvrf.schema.cvrf._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.icasi.cvrf.schema.cvrf._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.icasi.cvrf.schema.cvrf._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cvrfdoc }
     * 
     */
    public Cvrfdoc createCvrfdoc() {
        return new Cvrfdoc();
    }

    /**
     * Create an instance of {@link Cvrfdoc.Acknowledgments }
     * 
     */
    public Cvrfdoc.Acknowledgments createCvrfdocAcknowledgments() {
        return new Cvrfdoc.Acknowledgments();
    }

    /**
     * Create an instance of {@link Cvrfdoc.Acknowledgments.Acknowledgment }
     * 
     */
    public Cvrfdoc.Acknowledgments.Acknowledgment createCvrfdocAcknowledgmentsAcknowledgment() {
        return new Cvrfdoc.Acknowledgments.Acknowledgment();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentReferences }
     * 
     */
    public Cvrfdoc.DocumentReferences createCvrfdocDocumentReferences() {
        return new Cvrfdoc.DocumentReferences();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentReferences.Reference }
     * 
     */
    public Cvrfdoc.DocumentReferences.Reference createCvrfdocDocumentReferencesReference() {
        return new Cvrfdoc.DocumentReferences.Reference();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentNotes }
     * 
     */
    public Cvrfdoc.DocumentNotes createCvrfdocDocumentNotes() {
        return new Cvrfdoc.DocumentNotes();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking }
     * 
     */
    public Cvrfdoc.DocumentTracking createCvrfdocDocumentTracking() {
        return new Cvrfdoc.DocumentTracking();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.Generator }
     * 
     */
    public Cvrfdoc.DocumentTracking.Generator createCvrfdocDocumentTrackingGenerator() {
        return new Cvrfdoc.DocumentTracking.Generator();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.RevisionHistory }
     * 
     */
    public Cvrfdoc.DocumentTracking.RevisionHistory createCvrfdocDocumentTrackingRevisionHistory() {
        return new Cvrfdoc.DocumentTracking.RevisionHistory();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.RevisionHistory.Revision }
     * 
     */
    public Cvrfdoc.DocumentTracking.RevisionHistory.Revision createCvrfdocDocumentTrackingRevisionHistoryRevision() {
        return new Cvrfdoc.DocumentTracking.RevisionHistory.Revision();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.Identification }
     * 
     */
    public Cvrfdoc.DocumentTracking.Identification createCvrfdocDocumentTrackingIdentification() {
        return new Cvrfdoc.DocumentTracking.Identification();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentPublisher }
     * 
     */
    public Cvrfdoc.DocumentPublisher createCvrfdocDocumentPublisher() {
        return new Cvrfdoc.DocumentPublisher();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTitle }
     * 
     */
    public Cvrfdoc.DocumentTitle createCvrfdocDocumentTitle() {
        return new Cvrfdoc.DocumentTitle();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentType }
     * 
     */
    public Cvrfdoc.DocumentType createCvrfdocDocumentType() {
        return new Cvrfdoc.DocumentType();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentDistribution }
     * 
     */
    public Cvrfdoc.DocumentDistribution createCvrfdocDocumentDistribution() {
        return new Cvrfdoc.DocumentDistribution();
    }

    /**
     * Create an instance of {@link Cvrfdoc.AggregateSeverity }
     * 
     */
    public Cvrfdoc.AggregateSeverity createCvrfdocAggregateSeverity() {
        return new Cvrfdoc.AggregateSeverity();
    }

    /**
     * Create an instance of {@link Cvrfdoc.Acknowledgments.Acknowledgment.Name }
     * 
     */
    public Cvrfdoc.Acknowledgments.Acknowledgment.Name createCvrfdocAcknowledgmentsAcknowledgmentName() {
        return new Cvrfdoc.Acknowledgments.Acknowledgment.Name();
    }

    /**
     * Create an instance of {@link Cvrfdoc.Acknowledgments.Acknowledgment.Organization }
     * 
     */
    public Cvrfdoc.Acknowledgments.Acknowledgment.Organization createCvrfdocAcknowledgmentsAcknowledgmentOrganization() {
        return new Cvrfdoc.Acknowledgments.Acknowledgment.Organization();
    }

    /**
     * Create an instance of {@link Cvrfdoc.Acknowledgments.Acknowledgment.Description }
     * 
     */
    public Cvrfdoc.Acknowledgments.Acknowledgment.Description createCvrfdocAcknowledgmentsAcknowledgmentDescription() {
        return new Cvrfdoc.Acknowledgments.Acknowledgment.Description();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentReferences.Reference.Description }
     * 
     */
    public Cvrfdoc.DocumentReferences.Reference.Description createCvrfdocDocumentReferencesReferenceDescription() {
        return new Cvrfdoc.DocumentReferences.Reference.Description();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentNotes.Note }
     * 
     */
    public Cvrfdoc.DocumentNotes.Note createCvrfdocDocumentNotesNote() {
        return new Cvrfdoc.DocumentNotes.Note();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.Generator.Engine }
     * 
     */
    public Cvrfdoc.DocumentTracking.Generator.Engine createCvrfdocDocumentTrackingGeneratorEngine() {
        return new Cvrfdoc.DocumentTracking.Generator.Engine();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.RevisionHistory.Revision.Description }
     * 
     */
    public Cvrfdoc.DocumentTracking.RevisionHistory.Revision.Description createCvrfdocDocumentTrackingRevisionHistoryRevisionDescription() {
        return new Cvrfdoc.DocumentTracking.RevisionHistory.Revision.Description();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.Identification.ID }
     * 
     */
    public Cvrfdoc.DocumentTracking.Identification.ID createCvrfdocDocumentTrackingIdentificationID() {
        return new Cvrfdoc.DocumentTracking.Identification.ID();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentTracking.Identification.Alias }
     * 
     */
    public Cvrfdoc.DocumentTracking.Identification.Alias createCvrfdocDocumentTrackingIdentificationAlias() {
        return new Cvrfdoc.DocumentTracking.Identification.Alias();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentPublisher.ContactDetails }
     * 
     */
    public Cvrfdoc.DocumentPublisher.ContactDetails createCvrfdocDocumentPublisherContactDetails() {
        return new Cvrfdoc.DocumentPublisher.ContactDetails();
    }

    /**
     * Create an instance of {@link Cvrfdoc.DocumentPublisher.IssuingAuthority }
     * 
     */
    public Cvrfdoc.DocumentPublisher.IssuingAuthority createCvrfdocDocumentPublisherIssuingAuthority() {
        return new Cvrfdoc.DocumentPublisher.IssuingAuthority();
    }

}
