//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package gov.nist.scap.schema.scap_core._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Identifies a tool and any associated information about the tool, such as signature versions, that indicate the tool is capable or properly detecting and/or remdiating the vulnerability or misconfiguration
 * 
 * <p>Java class for assessmentMethodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assessmentMethodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assessment-check" type="{http://scap.nist.gov/schema/scap-core/1.0}checkReferenceType"/>
 *         &lt;element name="assessment-engine" type="{http://scap.nist.gov/schema/scap-core/1.0}cpeNamePatternType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assessmentMethodType", propOrder = {
    "assessmentCheck",
    "assessmentEngine"
})
@XmlSeeAlso({
    IdentifyableAssessmentMethodType.class
})
public class AssessmentMethodType {

    @XmlElement(name = "assessment-check", required = true)
    protected CheckReferenceType assessmentCheck;
    @XmlElement(name = "assessment-engine")
    protected List<String> assessmentEngine;

    /**
     * Gets the value of the assessmentCheck property.
     * 
     * @return
     *     possible object is
     *     {@link CheckReferenceType }
     *     
     */
    public CheckReferenceType getAssessmentCheck() {
        return assessmentCheck;
    }

    /**
     * Sets the value of the assessmentCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckReferenceType }
     *     
     */
    public void setAssessmentCheck(CheckReferenceType value) {
        this.assessmentCheck = value;
    }

    /**
     * Gets the value of the assessmentEngine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessmentEngine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessmentEngine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAssessmentEngine() {
        if (assessmentEngine == null) {
            assessmentEngine = new ArrayList<String>();
        }
        return this.assessmentEngine;
    }

}
