//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mitre.cybox.objects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Address_QNAME = new QName("http://cybox.mitre.org/objects#AddressObject-2", "Address");
    private final static QName _Process_QNAME = new QName("http://cybox.mitre.org/objects#ProcessObject-2", "Process");
    private final static QName _DNSRecord_QNAME = new QName("http://cybox.mitre.org/objects#DNSRecordObject-2", "DNS_Record");
    private final static QName _CodeObject_QNAME = new QName("http://cybox.mitre.org/objects#CodeObject-2", "Code_Object");
    private final static QName _Hostname_QNAME = new QName("http://cybox.mitre.org/objects#HostnameObject-1", "Hostname");
    private final static QName _System_QNAME = new QName("http://cybox.mitre.org/objects#SystemObject-2", "System");
    private final static QName _HTTPSession_QNAME = new QName("http://cybox.mitre.org/objects#HTTPSessionObject-2", "HTTP_Session");
    private final static QName _NetworkConnection_QNAME = new QName("http://cybox.mitre.org/objects#NetworkConnectionObject-2", "Network_Connection");
    private final static QName _Port_QNAME = new QName("http://cybox.mitre.org/objects#PortObject-2", "Port");
    private final static QName _File_QNAME = new QName("http://cybox.mitre.org/objects#FileObject-2", "File");
    private final static QName _DNSQuery_QNAME = new QName("http://cybox.mitre.org/objects#DNSQueryObject-2", "DNS_Query");
    private final static QName _SocketAddress_QNAME = new QName("http://cybox.mitre.org/objects#SocketAddressObject-1", "Socket_Address");
    private final static QName _URI_QNAME = new QName("http://cybox.mitre.org/objects#URIObject-2", "URI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mitre.cybox.objects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeObjectType }
     * 
     */
    public CodeObjectType createCodeObjectType() {
        return new CodeObjectType();
    }

    /**
     * Create an instance of {@link CodeSegmentXORType }
     * 
     */
    public CodeSegmentXORType createCodeSegmentXORType() {
        return new CodeSegmentXORType();
    }

    /**
     * Create an instance of {@link TargetedPlatformsType }
     * 
     */
    public TargetedPlatformsType createTargetedPlatformsType() {
        return new TargetedPlatformsType();
    }

    /**
     * Create an instance of {@link CodeLanguageType }
     * 
     */
    public CodeLanguageType createCodeLanguageType() {
        return new CodeLanguageType();
    }

    /**
     * Create an instance of {@link CodeTypeType }
     * 
     */
    public CodeTypeType createCodeTypeType() {
        return new CodeTypeType();
    }

    /**
     * Create an instance of {@link CodePurposeType }
     * 
     */
    public CodePurposeType createCodePurposeType() {
        return new CodePurposeType();
    }

    /**
     * Create an instance of {@link ProcessorTypeType }
     * 
     */
    public ProcessorTypeType createProcessorTypeType() {
        return new ProcessorTypeType();
    }

    /**
     * Create an instance of {@link ProcessObjectType }
     * 
     */
    public ProcessObjectType createProcessObjectType() {
        return new ProcessObjectType();
    }

    /**
     * Create an instance of {@link ChildPIDListType }
     * 
     */
    public ChildPIDListType createChildPIDListType() {
        return new ChildPIDListType();
    }

    /**
     * Create an instance of {@link NetworkConnectionListType }
     * 
     */
    public NetworkConnectionListType createNetworkConnectionListType() {
        return new NetworkConnectionListType();
    }

    /**
     * Create an instance of {@link PortListType }
     * 
     */
    public PortListType createPortListType() {
        return new PortListType();
    }

    /**
     * Create an instance of {@link ImageInfoType }
     * 
     */
    public ImageInfoType createImageInfoType() {
        return new ImageInfoType();
    }

    /**
     * Create an instance of {@link ArgumentListType }
     * 
     */
    public ArgumentListType createArgumentListType() {
        return new ArgumentListType();
    }

    /**
     * Create an instance of {@link PortObjectType }
     * 
     */
    public PortObjectType createPortObjectType() {
        return new PortObjectType();
    }

    /**
     * Create an instance of {@link NetworkConnectionObjectType }
     * 
     */
    public NetworkConnectionObjectType createNetworkConnectionObjectType() {
        return new NetworkConnectionObjectType();
    }

    /**
     * Create an instance of {@link Layer7ConnectionsType }
     * 
     */
    public Layer7ConnectionsType createLayer7ConnectionsType() {
        return new Layer7ConnectionsType();
    }

    /**
     * Create an instance of {@link Layer7ProtocolType }
     * 
     */
    public Layer7ProtocolType createLayer7ProtocolType() {
        return new Layer7ProtocolType();
    }

    /**
     * Create an instance of {@link Layer3ProtocolType }
     * 
     */
    public Layer3ProtocolType createLayer3ProtocolType() {
        return new Layer3ProtocolType();
    }

    /**
     * Create an instance of {@link HTTPSessionObjectType }
     * 
     */
    public HTTPSessionObjectType createHTTPSessionObjectType() {
        return new HTTPSessionObjectType();
    }

    /**
     * Create an instance of {@link HostFieldType }
     * 
     */
    public HostFieldType createHostFieldType() {
        return new HostFieldType();
    }

    /**
     * Create an instance of {@link HTTPStatusLineType }
     * 
     */
    public HTTPStatusLineType createHTTPStatusLineType() {
        return new HTTPStatusLineType();
    }

    /**
     * Create an instance of {@link HTTPMethodType }
     * 
     */
    public HTTPMethodType createHTTPMethodType() {
        return new HTTPMethodType();
    }

    /**
     * Create an instance of {@link HTTPRequestResponseType }
     * 
     */
    public HTTPRequestResponseType createHTTPRequestResponseType() {
        return new HTTPRequestResponseType();
    }

    /**
     * Create an instance of {@link HTTPRequestHeaderType }
     * 
     */
    public HTTPRequestHeaderType createHTTPRequestHeaderType() {
        return new HTTPRequestHeaderType();
    }

    /**
     * Create an instance of {@link HTTPRequestHeaderFieldsType }
     * 
     */
    public HTTPRequestHeaderFieldsType createHTTPRequestHeaderFieldsType() {
        return new HTTPRequestHeaderFieldsType();
    }

    /**
     * Create an instance of {@link HTTPServerResponseType }
     * 
     */
    public HTTPServerResponseType createHTTPServerResponseType() {
        return new HTTPServerResponseType();
    }

    /**
     * Create an instance of {@link HTTPMessageType }
     * 
     */
    public HTTPMessageType createHTTPMessageType() {
        return new HTTPMessageType();
    }

    /**
     * Create an instance of {@link HTTPClientRequestType }
     * 
     */
    public HTTPClientRequestType createHTTPClientRequestType() {
        return new HTTPClientRequestType();
    }

    /**
     * Create an instance of {@link HTTPRequestLineType }
     * 
     */
    public HTTPRequestLineType createHTTPRequestLineType() {
        return new HTTPRequestLineType();
    }

    /**
     * Create an instance of {@link HTTPResponseHeaderType }
     * 
     */
    public HTTPResponseHeaderType createHTTPResponseHeaderType() {
        return new HTTPResponseHeaderType();
    }

    /**
     * Create an instance of {@link HTTPResponseHeaderFieldsType }
     * 
     */
    public HTTPResponseHeaderFieldsType createHTTPResponseHeaderFieldsType() {
        return new HTTPResponseHeaderFieldsType();
    }

    /**
     * Create an instance of {@link AddressObjectType }
     * 
     */
    public AddressObjectType createAddressObjectType() {
        return new AddressObjectType();
    }

    /**
     * Create an instance of {@link URIObjectType }
     * 
     */
    public URIObjectType createURIObjectType() {
        return new URIObjectType();
    }

    /**
     * Create an instance of {@link DNSQueryObjectType }
     * 
     */
    public DNSQueryObjectType createDNSQueryObjectType() {
        return new DNSQueryObjectType();
    }

    /**
     * Create an instance of {@link DNSRecordType }
     * 
     */
    public DNSRecordType createDNSRecordType() {
        return new DNSRecordType();
    }

    /**
     * Create an instance of {@link DNSQuestionType }
     * 
     */
    public DNSQuestionType createDNSQuestionType() {
        return new DNSQuestionType();
    }

    /**
     * Create an instance of {@link DNSResourceRecordsType }
     * 
     */
    public DNSResourceRecordsType createDNSResourceRecordsType() {
        return new DNSResourceRecordsType();
    }

    /**
     * Create an instance of {@link DNSRecordObjectType }
     * 
     */
    public DNSRecordObjectType createDNSRecordObjectType() {
        return new DNSRecordObjectType();
    }

    /**
     * Create an instance of {@link SocketAddressObjectType }
     * 
     */
    public SocketAddressObjectType createSocketAddressObjectType() {
        return new SocketAddressObjectType();
    }

    /**
     * Create an instance of {@link HostnameObjectType }
     * 
     */
    public HostnameObjectType createHostnameObjectType() {
        return new HostnameObjectType();
    }

    /**
     * Create an instance of {@link SystemObjectType }
     * 
     */
    public SystemObjectType createSystemObjectType() {
        return new SystemObjectType();
    }

    /**
     * Create an instance of {@link NetworkInterfaceType }
     * 
     */
    public NetworkInterfaceType createNetworkInterfaceType() {
        return new NetworkInterfaceType();
    }

    /**
     * Create an instance of {@link OSType }
     * 
     */
    public OSType createOSType() {
        return new OSType();
    }

    /**
     * Create an instance of {@link BitnessType }
     * 
     */
    public BitnessType createBitnessType() {
        return new BitnessType();
    }

    /**
     * Create an instance of {@link ProcessorArchType }
     * 
     */
    public ProcessorArchType createProcessorArchType() {
        return new ProcessorArchType();
    }

    /**
     * Create an instance of {@link BIOSInfoType }
     * 
     */
    public BIOSInfoType createBIOSInfoType() {
        return new BIOSInfoType();
    }

    /**
     * Create an instance of {@link IPInfoListType }
     * 
     */
    public IPInfoListType createIPInfoListType() {
        return new IPInfoListType();
    }

    /**
     * Create an instance of {@link IPGatewayListType }
     * 
     */
    public IPGatewayListType createIPGatewayListType() {
        return new IPGatewayListType();
    }

    /**
     * Create an instance of {@link DHCPServerListType }
     * 
     */
    public DHCPServerListType createDHCPServerListType() {
        return new DHCPServerListType();
    }

    /**
     * Create an instance of {@link NetworkInterfaceListType }
     * 
     */
    public NetworkInterfaceListType createNetworkInterfaceListType() {
        return new NetworkInterfaceListType();
    }

    /**
     * Create an instance of {@link IPInfoType }
     * 
     */
    public IPInfoType createIPInfoType() {
        return new IPInfoType();
    }

    /**
     * Create an instance of {@link FileObjectType }
     * 
     */
    public FileObjectType createFileObjectType() {
        return new FileObjectType();
    }

    /**
     * Create an instance of {@link PackerListType }
     * 
     */
    public PackerListType createPackerListType() {
        return new PackerListType();
    }

    /**
     * Create an instance of {@link FilePathType }
     * 
     */
    public FilePathType createFilePathType() {
        return new FilePathType();
    }

    /**
     * Create an instance of {@link PackerClassType }
     * 
     */
    public PackerClassType createPackerClassType() {
        return new PackerClassType();
    }

    /**
     * Create an instance of {@link EPJumpCodeType }
     * 
     */
    public EPJumpCodeType createEPJumpCodeType() {
        return new EPJumpCodeType();
    }

    /**
     * Create an instance of {@link PackerType }
     * 
     */
    public PackerType createPackerType() {
        return new PackerType();
    }

    /**
     * Create an instance of {@link EntryPointSignatureListType }
     * 
     */
    public EntryPointSignatureListType createEntryPointSignatureListType() {
        return new EntryPointSignatureListType();
    }

    /**
     * Create an instance of {@link SymLinksListType }
     * 
     */
    public SymLinksListType createSymLinksListType() {
        return new SymLinksListType();
    }

    /**
     * Create an instance of {@link EntryPointSignatureType }
     * 
     */
    public EntryPointSignatureType createEntryPointSignatureType() {
        return new EntryPointSignatureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#AddressObject-2", name = "Address")
    public JAXBElement<AddressObjectType> createAddress(AddressObjectType value) {
        return new JAXBElement<AddressObjectType>(_Address_QNAME, AddressObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#ProcessObject-2", name = "Process")
    public JAXBElement<ProcessObjectType> createProcess(ProcessObjectType value) {
        return new JAXBElement<ProcessObjectType>(_Process_QNAME, ProcessObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DNSRecordObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#DNSRecordObject-2", name = "DNS_Record")
    public JAXBElement<DNSRecordObjectType> createDNSRecord(DNSRecordObjectType value) {
        return new JAXBElement<DNSRecordObjectType>(_DNSRecord_QNAME, DNSRecordObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#CodeObject-2", name = "Code_Object")
    public JAXBElement<CodeObjectType> createCodeObject(CodeObjectType value) {
        return new JAXBElement<CodeObjectType>(_CodeObject_QNAME, CodeObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostnameObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#HostnameObject-1", name = "Hostname")
    public JAXBElement<HostnameObjectType> createHostname(HostnameObjectType value) {
        return new JAXBElement<HostnameObjectType>(_Hostname_QNAME, HostnameObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#SystemObject-2", name = "System")
    public JAXBElement<SystemObjectType> createSystem(SystemObjectType value) {
        return new JAXBElement<SystemObjectType>(_System_QNAME, SystemObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HTTPSessionObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#HTTPSessionObject-2", name = "HTTP_Session")
    public JAXBElement<HTTPSessionObjectType> createHTTPSession(HTTPSessionObjectType value) {
        return new JAXBElement<HTTPSessionObjectType>(_HTTPSession_QNAME, HTTPSessionObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkConnectionObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#NetworkConnectionObject-2", name = "Network_Connection")
    public JAXBElement<NetworkConnectionObjectType> createNetworkConnection(NetworkConnectionObjectType value) {
        return new JAXBElement<NetworkConnectionObjectType>(_NetworkConnection_QNAME, NetworkConnectionObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#PortObject-2", name = "Port")
    public JAXBElement<PortObjectType> createPort(PortObjectType value) {
        return new JAXBElement<PortObjectType>(_Port_QNAME, PortObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#FileObject-2", name = "File")
    public JAXBElement<FileObjectType> createFile(FileObjectType value) {
        return new JAXBElement<FileObjectType>(_File_QNAME, FileObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DNSQueryObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#DNSQueryObject-2", name = "DNS_Query")
    public JAXBElement<DNSQueryObjectType> createDNSQuery(DNSQueryObjectType value) {
        return new JAXBElement<DNSQueryObjectType>(_DNSQuery_QNAME, DNSQueryObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SocketAddressObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#SocketAddressObject-1", name = "Socket_Address")
    public JAXBElement<SocketAddressObjectType> createSocketAddress(SocketAddressObjectType value) {
        return new JAXBElement<SocketAddressObjectType>(_SocketAddress_QNAME, SocketAddressObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link URIObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cybox.mitre.org/objects#URIObject-2", name = "URI")
    public JAXBElement<URIObjectType> createURI(URIObjectType value) {
        return new JAXBElement<URIObjectType>(_URI_QNAME, URIObjectType.class, null, value);
    }

}
