//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The BehaviorPurposeType captures the purpose behind a malware Behavior.
 * 
 * <p>Java class for BehaviorPurposeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BehaviorPurposeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Vulnerability_Exploit" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}ExploitType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BehaviorPurposeType", propOrder = {
    "description",
    "vulnerabilityExploit"
})
public class BehaviorPurposeType {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Vulnerability_Exploit")
    protected ExploitType vulnerabilityExploit;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the vulnerabilityExploit property.
     * 
     * @return
     *     possible object is
     *     {@link ExploitType }
     *     
     */
    public ExploitType getVulnerabilityExploit() {
        return vulnerabilityExploit;
    }

    /**
     * Sets the value of the vulnerabilityExploit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExploitType }
     *     
     */
    public void setVulnerabilityExploit(ExploitType value) {
        this.vulnerabilityExploit = value;
    }

}
