//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_bundle_4;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.mitre.cybox.common_2.ControlledVocabularyStringType;


/**
 * The CandidateIndicatorType provides a way of defining a MAEC entity-based Candidate Indicator, which specifies the particular components that may signify the presence of the malware instance on a host system or network.
 * 
 * <p>Java class for CandidateIndicatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CandidateIndicatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Importance" type="{http://cybox.mitre.org/common-2}ControlledVocabularyStringType" minOccurs="0"/>
 *         &lt;element name="Numeric_Importance" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Malware_Entity" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}MalwareEntityType" minOccurs="0"/>
 *         &lt;element name="Composition" type="{http://maec.mitre.org/XMLSchema/maec-bundle-4}CandidateIndicatorCompositionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="creation_datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="lastupdate_datetime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CandidateIndicatorType", propOrder = {
    "importance",
    "numericImportance",
    "author",
    "description",
    "malwareEntity",
    "composition"
})
public class CandidateIndicatorType {

    @XmlElement(name = "Importance")
    protected ControlledVocabularyStringType importance;
    @XmlElement(name = "Numeric_Importance")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numericImportance;
    @XmlElement(name = "Author")
    protected String author;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Malware_Entity")
    protected MalwareEntityType malwareEntity;
    @XmlElement(name = "Composition")
    protected CandidateIndicatorCompositionType composition;
    @XmlAttribute(name = "id", required = true)
    protected QName id;
    @XmlAttribute(name = "creation_datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDatetime;
    @XmlAttribute(name = "lastupdate_datetime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastupdateDatetime;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public ControlledVocabularyStringType getImportance() {
        return importance;
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public void setImportance(ControlledVocabularyStringType value) {
        this.importance = value;
    }

    /**
     * Gets the value of the numericImportance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumericImportance() {
        return numericImportance;
    }

    /**
     * Sets the value of the numericImportance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumericImportance(BigInteger value) {
        this.numericImportance = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the malwareEntity property.
     * 
     * @return
     *     possible object is
     *     {@link MalwareEntityType }
     *     
     */
    public MalwareEntityType getMalwareEntity() {
        return malwareEntity;
    }

    /**
     * Sets the value of the malwareEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MalwareEntityType }
     *     
     */
    public void setMalwareEntity(MalwareEntityType value) {
        this.malwareEntity = value;
    }

    /**
     * Gets the value of the composition property.
     * 
     * @return
     *     possible object is
     *     {@link CandidateIndicatorCompositionType }
     *     
     */
    public CandidateIndicatorCompositionType getComposition() {
        return composition;
    }

    /**
     * Sets the value of the composition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CandidateIndicatorCompositionType }
     *     
     */
    public void setComposition(CandidateIndicatorCompositionType value) {
        this.composition = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setId(QName value) {
        this.id = value;
    }

    /**
     * Gets the value of the creationDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDatetime() {
        return creationDatetime;
    }

    /**
     * Sets the value of the creationDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDatetime(XMLGregorianCalendar value) {
        this.creationDatetime = value;
    }

    /**
     * Gets the value of the lastupdateDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastupdateDatetime() {
        return lastupdateDatetime;
    }

    /**
     * Sets the value of the lastupdateDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastupdateDatetime(XMLGregorianCalendar value) {
        this.lastupdateDatetime = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
