//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package oasis.names.tc.ciq.xpil._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElectronicAddressIdentifierTypeList.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ElectronicAddressIdentifierTypeList">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="AIM"/>
 *     &lt;enumeration value="EMAIL"/>
 *     &lt;enumeration value="GOOGLE"/>
 *     &lt;enumeration value="GIZMO"/>
 *     &lt;enumeration value="ICQ"/>
 *     &lt;enumeration value="JABBER"/>
 *     &lt;enumeration value="MSN"/>
 *     &lt;enumeration value="SIP"/>
 *     &lt;enumeration value="SKYPE"/>
 *     &lt;enumeration value="URL"/>
 *     &lt;enumeration value="XRI"/>
 *     &lt;enumeration value="YAHOO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ElectronicAddressIdentifierTypeList")
@XmlEnum
public enum ElectronicAddressIdentifierTypeList {

    AIM,
    EMAIL,
    GOOGLE,
    GIZMO,
    ICQ,
    JABBER,
    MSN,
    SIP,
    SKYPE,
    URL,
    XRI,
    YAHOO;

    public String value() {
        return name();
    }

    public static ElectronicAddressIdentifierTypeList fromValue(String v) {
        return valueOf(v);
    }

}
