//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HTTPActionNameEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HTTPActionNameEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="send http get request"/>
 *     &lt;enumeration value="send http head request"/>
 *     &lt;enumeration value="send http post request"/>
 *     &lt;enumeration value="send http put request"/>
 *     &lt;enumeration value="send http delete request"/>
 *     &lt;enumeration value="send http trace request"/>
 *     &lt;enumeration value="send http options request"/>
 *     &lt;enumeration value="send http connect request"/>
 *     &lt;enumeration value="send http patch request"/>
 *     &lt;enumeration value="receive http response"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HTTPActionNameEnum-1.0")
@XmlEnum
public enum HTTPActionNameEnum10 {


    /**
     * Specifies the defined action of sending an HTTP GET client request to an existing server.
     * 
     */
    @XmlEnumValue("send http get request")
    SEND_HTTP_GET_REQUEST("send http get request"),

    /**
     * The 'send http head request' value specifies the defined action of sending an HTTP HEAD client request to an existing server.
     * 
     */
    @XmlEnumValue("send http head request")
    SEND_HTTP_HEAD_REQUEST("send http head request"),

    /**
     * The 'send http post request' value specifies the defined action of sending an HTTP HEAD client request to an existing server.
     * 
     */
    @XmlEnumValue("send http post request")
    SEND_HTTP_POST_REQUEST("send http post request"),

    /**
     * The 'send http put request' value specifies the defined action of sending an HTTP PUT client request to an existing server.
     * 
     */
    @XmlEnumValue("send http put request")
    SEND_HTTP_PUT_REQUEST("send http put request"),

    /**
     * The 'send http delete request' value specifies the defined action of sending an HTTP DELETE client request to an existing server.
     * 
     */
    @XmlEnumValue("send http delete request")
    SEND_HTTP_DELETE_REQUEST("send http delete request"),

    /**
     * The 'send http trace request' value specifies the defined action of sending an HTTP TRACE client request to an existing server.
     * 
     */
    @XmlEnumValue("send http trace request")
    SEND_HTTP_TRACE_REQUEST("send http trace request"),

    /**
     * The 'send http options request' value specifies the defined action of sending an HTTP OPTIONS client request to an existing server.
     * 
     */
    @XmlEnumValue("send http options request")
    SEND_HTTP_OPTIONS_REQUEST("send http options request"),

    /**
     * The 'send http connect request' value specifies the defined action of sending an HTTP CONNECT client request to an existing server.
     * 
     */
    @XmlEnumValue("send http connect request")
    SEND_HTTP_CONNECT_REQUEST("send http connect request"),

    /**
     * The 'send http patch request' value specifies the defined action of sending an HTTP PATCH client request to an existing server.
     * 
     */
    @XmlEnumValue("send http patch request")
    SEND_HTTP_PATCH_REQUEST("send http patch request"),

    /**
     * The 'receive http response' value specifies the defined action of receiving an HTTP server response for a prior HTTP request.
     * 
     */
    @XmlEnumValue("receive http response")
    RECEIVE_HTTP_RESPONSE("receive http response");
    private final String value;

    HTTPActionNameEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HTTPActionNameEnum10 fromValue(String v) {
        for (HTTPActionNameEnum10 c: HTTPActionNameEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
