//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityDegradationTacticalObjectivesEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityDegradationTacticalObjectivesEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stop execution of security program"/>
 *     &lt;enumeration value="disable firewall"/>
 *     &lt;enumeration value="disable access right checking"/>
 *     &lt;enumeration value="disable kernel patching protection"/>
 *     &lt;enumeration value="prevent access to security websites"/>
 *     &lt;enumeration value="remove sms warning messages"/>
 *     &lt;enumeration value="modify security program configuration"/>
 *     &lt;enumeration value="prevent security program from running"/>
 *     &lt;enumeration value="disable system update services/daemons"/>
 *     &lt;enumeration value="disable system service pack/patch installation"/>
 *     &lt;enumeration value="disable system file overwrite protection"/>
 *     &lt;enumeration value="disable privilege limiting"/>
 *     &lt;enumeration value="gather security product info"/>
 *     &lt;enumeration value="disable os security alerts"/>
 *     &lt;enumeration value="disable user account control"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecurityDegradationTacticalObjectivesEnum-1.0")
@XmlEnum
public enum SecurityDegradationTacticalObjectivesEnum10 {


    /**
     * The 'stop execution of security program' value indicates that the malware instance is able to stop one or more security programs that may already be executing on a system.
     * 
     */
    @XmlEnumValue("stop execution of security program")
    STOP_EXECUTION_OF_SECURITY_PROGRAM("stop execution of security program"),

    /**
     * The 'disable firewall' value indicates that the malware instance is able to evade or disable the host-based firewall or otherwise prevent the blocking of network communications.
     * 
     */
    @XmlEnumValue("disable firewall")
    DISABLE_FIREWALL("disable firewall"),

    /**
     * The 'disable access right checking' value indicates that the malware instance is able to bbypass, disable, or modify the access tokens or access control lists, thereby enabling the malware to read, write, or execute a file with one or more of these controls set.
     * 
     */
    @XmlEnumValue("disable access right checking")
    DISABLE_ACCESS_RIGHT_CHECKING("disable access right checking"),

    /**
     * The 'disable kernel patch protection' value indicates that the malware instance is able to bypass or disable PatchGuard; thus it is capable of operating at the same level as the kernel and kernel mode drivers (KMD).
     * 
     */
    @XmlEnumValue("disable kernel patching protection")
    DISABLE_KERNEL_PATCHING_PROTECTION("disable kernel patching protection"),

    /**
     * The 'prevent access to security websites' value indicates that the malware instance is able to prevent access from a system to one or more security vendor or security-related websites.
     * 
     */
    @XmlEnumValue("prevent access to security websites")
    PREVENT_ACCESS_TO_SECURITY_WEBSITES("prevent access to security websites"),

    /**
     * The 'remove sms warning messages' value indicates that the malware instance is able to capture the message body of incoming SMS messages and abort the broadcasting of a message that meets a certain criteria.
     * 
     */
    @XmlEnumValue("remove sms warning messages")
    REMOVE_SMS_WARNING_MESSAGES("remove sms warning messages"),

    /**
     * The 'modify security program configuration' value indicates that the malware instance is able to modify the configuration of one or more security programs running on a system in order to hamper their usefulness and ability to detect the malware instance.
     * 
     */
    @XmlEnumValue("modify security program configuration")
    MODIFY_SECURITY_PROGRAM_CONFIGURATION("modify security program configuration"),

    /**
     * The 'prevent security program from running' value indicates that the malware instance is able to prevent one or more security programs from running on a system.
     * 
     */
    @XmlEnumValue("prevent security program from running")
    PREVENT_SECURITY_PROGRAM_FROM_RUNNING("prevent security program from running"),

    /**
     * The 'disable system update services/daemons' value indicates that the malware instance is able to disable system update services or daemons that may be running on a system.
     * 
     */
    @XmlEnumValue("disable system update services/daemons")
    DISABLE_SYSTEM_UPDATE_SERVICES_DAEMONS("disable system update services/daemons"),

    /**
     * The 'disable system service pack/patch installation' value indicates that the malware instance is able to disable the system's ability to install service packs or patches.
     * 
     */
    @XmlEnumValue("disable system service pack/patch installation")
    DISABLE_SYSTEM_SERVICE_PACK_PATCH_INSTALLATION("disable system service pack/patch installation"),

    /**
     * The 'disable system file overwrite protection' value indicates that the malware instance is able to bypass or disable the Windows file protection feature; thus, enabling system files to be modified or replaced.
     * 
     */
    @XmlEnumValue("disable system file overwrite protection")
    DISABLE_SYSTEM_FILE_OVERWRITE_PROTECTION("disable system file overwrite protection"),

    /**
     * The 'disable privilege limiting' value indicates that the malware instance is able to bypass controls that limit the privileges that can be granted to a user or entity.
     * 
     */
    @XmlEnumValue("disable privilege limiting")
    DISABLE_PRIVILEGE_LIMITING("disable privilege limiting"),

    /**
     * The 'gather security product info' value indicates that the malware instance is able to gather information about the security products installed or running on a system.
     * 
     */
    @XmlEnumValue("gather security product info")
    GATHER_SECURITY_PRODUCT_INFO("gather security product info"),

    /**
     * The 'disable os security alerts' value indicates that the malware instance is able to evade or disable identification and/or notification of its presence by inherent features of the operating system.
     * 
     */
    @XmlEnumValue("disable os security alerts")
    DISABLE_OS_SECURITY_ALERTS("disable os security alerts"),

    /**
     * The 'disable user account control' value indicates that the malware instance is able to bypass or disable user account control (UAC); thus, enabling a user to run an application with elevated privileges.
     * 
     */
    @XmlEnumValue("disable user account control")
    DISABLE_USER_ACCOUNT_CONTROL("disable user account control");
    private final String value;

    SecurityDegradationTacticalObjectivesEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SecurityDegradationTacticalObjectivesEnum10 fromValue(String v) {
        for (SecurityDegradationTacticalObjectivesEnum10 c: SecurityDegradationTacticalObjectivesEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
