//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataExfiltrationTacticalObjectivesEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataExfiltrationTacticalObjectivesEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="exfiltrate via covert channel"/>
 *     &lt;enumeration value="exfiltrate via fax"/>
 *     &lt;enumeration value="exfiltrate via physical media"/>
 *     &lt;enumeration value="encrypt data"/>
 *     &lt;enumeration value="exfiltrate via network"/>
 *     &lt;enumeration value="hide data"/>
 *     &lt;enumeration value="package data"/>
 *     &lt;enumeration value="exfiltrate via dumpster dive"/>
 *     &lt;enumeration value="move data to staging server"/>
 *     &lt;enumeration value="exfiltrate via voip/phone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataExfiltrationTacticalObjectivesEnum-1.0")
@XmlEnum
public enum DataExfiltrationTacticalObjectivesEnum10 {


    /**
     * The 'exfiltrate via covert channel' value indicates that the malware instance is able to exfiltrate data using a covert channel.
     * 
     */
    @XmlEnumValue("exfiltrate via covert channel")
    EXFILTRATE_VIA_COVERT_CHANNEL("exfiltrate via covert channel"),

    /**
     * The 'exfiltrate via fax' value indicates that the malware instance is able to exfiltrate data using a fax system.
     * 
     */
    @XmlEnumValue("exfiltrate via fax")
    EXFILTRATE_VIA_FAX("exfiltrate via fax"),

    /**
     * The 'exfiltrate via physical media' value indicates that the malware instance is able to exfiltrate data using physical media (e.g., a USB drive).
     * 
     */
    @XmlEnumValue("exfiltrate via physical media")
    EXFILTRATE_VIA_PHYSICAL_MEDIA("exfiltrate via physical media"),

    /**
     * The 'encrypt data' value indicates that the malware instance is able to encrypt data that will be exfiltrated.
     * 
     */
    @XmlEnumValue("encrypt data")
    ENCRYPT_DATA("encrypt data"),

    /**
     * The 'exfiltrate via network' value indicates that the malware instance is able to exfiltrate data across the network.
     * 
     */
    @XmlEnumValue("exfiltrate via network")
    EXFILTRATE_VIA_NETWORK("exfiltrate via network"),

    /**
     * The 'hide data in other formats' value indicates that the malware instance is able to hide data that will be exfiltrated in other formats (also known as steganography).
     * 
     */
    @XmlEnumValue("hide data")
    HIDE_DATA("hide data"),

    /**
     * The 'package data' value indicates that the malware instance is able to package data for exfiltration.
     * 
     */
    @XmlEnumValue("package data")
    PACKAGE_DATA("package data"),

    /**
     * The 'exfiltrate via dumpster dive' value indicates that the malware instance is able to exfiltrate data via dumpster dive (i.e., encoded data printed by malware is viewed as garbage and thrown away to then be physically picked up).
     * 
     */
    @XmlEnumValue("exfiltrate via dumpster dive")
    EXFILTRATE_VIA_DUMPSTER_DIVE("exfiltrate via dumpster dive"),

    /**
     * The 'move data to staging server' value indicates that the malware instance is able to move data to be exfiltrated to a particular server to prepare for exfiltration.
     * 
     */
    @XmlEnumValue("move data to staging server")
    MOVE_DATA_TO_STAGING_SERVER("move data to staging server"),

    /**
     * The 'exfiltrate via VoIP/phone' value indicates that the malware instance is able to exfiltrate data (encoded as audio) using a phone system.  
     * 
     */
    @XmlEnumValue("exfiltrate via voip/phone")
    EXFILTRATE_VIA_VOIP_PHONE("exfiltrate via voip/phone");
    private final String value;

    DataExfiltrationTacticalObjectivesEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataExfiltrationTacticalObjectivesEnum10 fromValue(String v) {
        for (DataExfiltrationTacticalObjectivesEnum10 c: DataExfiltrationTacticalObjectivesEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
