//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrivilegeEscalationPropertiesEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrivilegeEscalationPropertiesEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="user privilege escalation type"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrivilegeEscalationPropertiesEnum-1.0")
@XmlEnum
public enum PrivilegeEscalationPropertiesEnum10 {


    /**
     * Recommended values are: 'horizontal', or 'vertical'.
     * 
     */
    @XmlEnumValue("user privilege escalation type")
    USER_PRIVILEGE_ESCALATION_TYPE("user privilege escalation type");
    private final String value;

    PrivilegeEscalationPropertiesEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrivilegeEscalationPropertiesEnum10 fromValue(String v) {
        for (PrivilegeEscalationPropertiesEnum10 c: PrivilegeEscalationPropertiesEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
