//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrivilegeEscalationStrategicObjectivesEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrivilegeEscalationStrategicObjectivesEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="impersonate user"/>
 *     &lt;enumeration value="escalate user privilege"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrivilegeEscalationStrategicObjectivesEnum-1.0")
@XmlEnum
public enum PrivilegeEscalationStrategicObjectivesEnum10 {


    /**
     * The 'impersonate user' value indicates that the malware instance is able to impersonate another user to operate within a different security context (also known as horizontal privilege escalation).
     * 
     */
    @XmlEnumValue("impersonate user")
    IMPERSONATE_USER("impersonate user"),

    /**
     * The 'escalate user privilege' indicates that the malware instance is able to obtain a higher level of access than intended by the system (also known as vertical privilege escalation).
     * 
     */
    @XmlEnumValue("escalate user privilege")
    ESCALATE_USER_PRIVILEGE("escalate user privilege");
    private final String value;

    PrivilegeEscalationStrategicObjectivesEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrivilegeEscalationStrategicObjectivesEnum10 fromValue(String v) {
        for (PrivilegeEscalationStrategicObjectivesEnum10 c: PrivilegeEscalationStrategicObjectivesEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
