//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessActionNameEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessActionNameEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="create process"/>
 *     &lt;enumeration value="kill process"/>
 *     &lt;enumeration value="create process as user"/>
 *     &lt;enumeration value="enumerate processes"/>
 *     &lt;enumeration value="open process"/>
 *     &lt;enumeration value="flush process instruction cache"/>
 *     &lt;enumeration value="get process current directory"/>
 *     &lt;enumeration value="set process current directory"/>
 *     &lt;enumeration value="get process environment variable"/>
 *     &lt;enumeration value="set process environment variable"/>
 *     &lt;enumeration value="sleep process"/>
 *     &lt;enumeration value="get process startupinfo"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcessActionNameEnum-1.0")
@XmlEnum
public enum ProcessActionNameEnum10 {


    /**
     * The 'create process' value specifies the defined action of creating a new process.
     * 
     */
    @XmlEnumValue("create process")
    CREATE_PROCESS("create process"),

    /**
     * The 'kill process' value specifies the defined action of killing an existing process.
     * 
     */
    @XmlEnumValue("kill process")
    KILL_PROCESS("kill process"),

    /**
     * The 'create process as user' value specifies the defined action of creating a new process in the security context of a specified user.
     * 
     */
    @XmlEnumValue("create process as user")
    CREATE_PROCESS_AS_USER("create process as user"),

    /**
     * The 'enumerate processes' value specifies the defined action of enumerating all of the running processes on a system.
     * 
     */
    @XmlEnumValue("enumerate processes")
    ENUMERATE_PROCESSES("enumerate processes"),

    /**
     * The 'open process' value specifies the defined action of opening an existing process.
     * 
     */
    @XmlEnumValue("open process")
    OPEN_PROCESS("open process"),

    /**
     * The 'flush process instruction cache' value specifies the defined action of flushing the instruction cache of an existing process.
     * 
     */
    @XmlEnumValue("flush process instruction cache")
    FLUSH_PROCESS_INSTRUCTION_CACHE("flush process instruction cache"),

    /**
     * The 'get process current directory' value specifies the defined action of getting the current directory of an existing process.
     * 
     */
    @XmlEnumValue("get process current directory")
    GET_PROCESS_CURRENT_DIRECTORY("get process current directory"),

    /**
     * The 'set process current directory' value specifies the defined action of setting the current directory of an existing process.
     * 
     */
    @XmlEnumValue("set process current directory")
    SET_PROCESS_CURRENT_DIRECTORY("set process current directory"),

    /**
     * The 'get process environment variable' value specifies the defined action of getting an environment variable used by an existing process.
     * 
     */
    @XmlEnumValue("get process environment variable")
    GET_PROCESS_ENVIRONMENT_VARIABLE("get process environment variable"),

    /**
     * The 'set process environment variable' value specifies the defined action of setting an environment variable used by an existing process.
     * 
     */
    @XmlEnumValue("set process environment variable")
    SET_PROCESS_ENVIRONMENT_VARIABLE("set process environment variable"),

    /**
     * The 'sleep process' value specifies the defined action of sleeping an existing process for some period of time.
     * 
     */
    @XmlEnumValue("sleep process")
    SLEEP_PROCESS("sleep process"),

    /**
     * Windows-specific.
     * 
     */
    @XmlEnumValue("get process startupinfo")
    GET_PROCESS_STARTUPINFO("get process startupinfo");
    private final String value;

    ProcessActionNameEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcessActionNameEnum10 fromValue(String v) {
        for (ProcessActionNameEnum10 c: ProcessActionNameEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
