//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 09:40:50 PM EDT 
//


package xml.metadatasharing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Digital signature object, used to hold information about digitally signed binaries with regards to the certificate used and its validity.
 * 
 * <p>Java class for digitalSignatureObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="digitalSignatureObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="certificateIssuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificateSubject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="certificateValidity" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="certificateRevocationTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="signingTimestamp" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                 &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CatalogSigned"/>
 *             &lt;enumeration value="CodeSigned"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "digitalSignatureObject", propOrder = {
    "certificateIssuer",
    "certificateSubject",
    "certificateValidity",
    "certificateRevocationTimestamp",
    "signingTimestamp"
})
public class DigitalSignatureObject {

    @XmlElement(required = true)
    protected String certificateIssuer;
    protected String certificateSubject;
    protected boolean certificateValidity;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar certificateRevocationTimestamp;
    protected DigitalSignatureObject.SigningTimestamp signingTimestamp;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the certificateIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateIssuer() {
        return certificateIssuer;
    }

    /**
     * Sets the value of the certificateIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateIssuer(String value) {
        this.certificateIssuer = value;
    }

    /**
     * Gets the value of the certificateSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateSubject() {
        return certificateSubject;
    }

    /**
     * Sets the value of the certificateSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateSubject(String value) {
        this.certificateSubject = value;
    }

    /**
     * Gets the value of the certificateValidity property.
     * 
     */
    public boolean isCertificateValidity() {
        return certificateValidity;
    }

    /**
     * Sets the value of the certificateValidity property.
     * 
     */
    public void setCertificateValidity(boolean value) {
        this.certificateValidity = value;
    }

    /**
     * Gets the value of the certificateRevocationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertificateRevocationTimestamp() {
        return certificateRevocationTimestamp;
    }

    /**
     * Sets the value of the certificateRevocationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertificateRevocationTimestamp(XMLGregorianCalendar value) {
        this.certificateRevocationTimestamp = value;
    }

    /**
     * Gets the value of the signingTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalSignatureObject.SigningTimestamp }
     *     
     */
    public DigitalSignatureObject.SigningTimestamp getSigningTimestamp() {
        return signingTimestamp;
    }

    /**
     * Sets the value of the signingTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalSignatureObject.SigningTimestamp }
     *     
     */
    public void setSigningTimestamp(DigitalSignatureObject.SigningTimestamp value) {
        this.signingTimestamp = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SigningTimestamp {

        @XmlValue
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "valid")
        protected Boolean valid;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the valid property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setValid(Boolean value) {
            this.valid = value;
        }

    }

}
