//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.maec.xmlschema.maec_package_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The NetworkInfrastructureType captures specific details about the network infrastructure used in the malware analysis environment.
 * 
 * <p>Java class for NetworkInfrastructureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkInfrastructureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Captured_Protocols" type="{http://maec.mitre.org/XMLSchema/maec-package-2}CapturedProtocolListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkInfrastructureType", propOrder = {
    "capturedProtocols"
})
public class NetworkInfrastructureType {

    @XmlElement(name = "Captured_Protocols", required = true)
    protected CapturedProtocolListType capturedProtocols;

    /**
     * Gets the value of the capturedProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link CapturedProtocolListType }
     *     
     */
    public CapturedProtocolListType getCapturedProtocols() {
        return capturedProtocols;
    }

    /**
     * Sets the value of the capturedProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapturedProtocolListType }
     *     
     */
    public void setCapturedProtocols(CapturedProtocolListType value) {
        this.capturedProtocols = value;
    }

}
