//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.09 at 05:02:22 PM EDT 
//


package org.mitre.oval.xmlschema.oval_definitions_5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mitre.oval.xmlschema.oval_definitions_5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _State_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "state");
    private final static QName _Object_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "object");
    private final static QName _Definition_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "definition");
    private final static QName _LocalVariable_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "local_variable");
    private final static QName _ExternalVariable_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "external_variable");
    private final static QName _Variable_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "variable");
    private final static QName _Test_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "test");
    private final static QName _ConstantVariable_QNAME = new QName("http://oval.mitre.org/XMLSchema/oval-definitions-5", "constant_variable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mitre.oval.xmlschema.oval_definitions_5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LocalVariable }
     * 
     */
    public LocalVariable createLocalVariable() {
        return new LocalVariable();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link DefinitionType }
     * 
     */
    public DefinitionType createDefinitionType() {
        return new DefinitionType();
    }

    /**
     * Create an instance of {@link TestType }
     * 
     */
    public TestType createTestType() {
        return new TestType();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link ConstantVariable }
     * 
     */
    public ConstantVariable createConstantVariable() {
        return new ConstantVariable();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link OvalDefinitions }
     * 
     */
    public OvalDefinitions createOvalDefinitions() {
        return new OvalDefinitions();
    }

    /**
     * Create an instance of {@link DefinitionsType }
     * 
     */
    public DefinitionsType createDefinitionsType() {
        return new DefinitionsType();
    }

    /**
     * Create an instance of {@link TestsType }
     * 
     */
    public TestsType createTestsType() {
        return new TestsType();
    }

    /**
     * Create an instance of {@link ObjectsType }
     * 
     */
    public ObjectsType createObjectsType() {
        return new ObjectsType();
    }

    /**
     * Create an instance of {@link StatesType }
     * 
     */
    public StatesType createStatesType() {
        return new StatesType();
    }

    /**
     * Create an instance of {@link VariablesType }
     * 
     */
    public VariablesType createVariablesType() {
        return new VariablesType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link ExternalVariable }
     * 
     */
    public ExternalVariable createExternalVariable() {
        return new ExternalVariable();
    }

    /**
     * Create an instance of {@link EntityStateIPAddressType }
     * 
     */
    public EntityStateIPAddressType createEntityStateIPAddressType() {
        return new EntityStateIPAddressType();
    }

    /**
     * Create an instance of {@link EntityObjectAnySimpleType }
     * 
     */
    public EntityObjectAnySimpleType createEntityObjectAnySimpleType() {
        return new EntityObjectAnySimpleType();
    }

    /**
     * Create an instance of {@link EntityStateFieldType }
     * 
     */
    public EntityStateFieldType createEntityStateFieldType() {
        return new EntityStateFieldType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link EntityObjectFloatType }
     * 
     */
    public EntityObjectFloatType createEntityObjectFloatType() {
        return new EntityObjectFloatType();
    }

    /**
     * Create an instance of {@link PossibleRestrictionType }
     * 
     */
    public PossibleRestrictionType createPossibleRestrictionType() {
        return new PossibleRestrictionType();
    }

    /**
     * Create an instance of {@link EntityStateFloatType }
     * 
     */
    public EntityStateFloatType createEntityStateFloatType() {
        return new EntityStateFloatType();
    }

    /**
     * Create an instance of {@link AffectedType }
     * 
     */
    public AffectedType createAffectedType() {
        return new AffectedType();
    }

    /**
     * Create an instance of {@link EntityObjectBoolType }
     * 
     */
    public EntityObjectBoolType createEntityObjectBoolType() {
        return new EntityObjectBoolType();
    }

    /**
     * Create an instance of {@link RestrictionType }
     * 
     */
    public RestrictionType createRestrictionType() {
        return new RestrictionType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link SplitFunctionType }
     * 
     */
    public SplitFunctionType createSplitFunctionType() {
        return new SplitFunctionType();
    }

    /**
     * Create an instance of {@link ArithmeticFunctionType }
     * 
     */
    public ArithmeticFunctionType createArithmeticFunctionType() {
        return new ArithmeticFunctionType();
    }

    /**
     * Create an instance of {@link EntityStateIntType }
     * 
     */
    public EntityStateIntType createEntityStateIntType() {
        return new EntityStateIntType();
    }

    /**
     * Create an instance of {@link EntityObjectIPAddressStringType }
     * 
     */
    public EntityObjectIPAddressStringType createEntityObjectIPAddressStringType() {
        return new EntityObjectIPAddressStringType();
    }

    /**
     * Create an instance of {@link EntityObjectVersionType }
     * 
     */
    public EntityObjectVersionType createEntityObjectVersionType() {
        return new EntityObjectVersionType();
    }

    /**
     * Create an instance of {@link EntityObjectFieldType }
     * 
     */
    public EntityObjectFieldType createEntityObjectFieldType() {
        return new EntityObjectFieldType();
    }

    /**
     * Create an instance of {@link EscapeRegexFunctionType }
     * 
     */
    public EscapeRegexFunctionType createEscapeRegexFunctionType() {
        return new EscapeRegexFunctionType();
    }

    /**
     * Create an instance of {@link EntityStateIOSVersionType }
     * 
     */
    public EntityStateIOSVersionType createEntityStateIOSVersionType() {
        return new EntityStateIOSVersionType();
    }

    /**
     * Create an instance of {@link EntityStateVersionType }
     * 
     */
    public EntityStateVersionType createEntityStateVersionType() {
        return new EntityStateVersionType();
    }

    /**
     * Create an instance of {@link EntityObjectIntType }
     * 
     */
    public EntityObjectIntType createEntityObjectIntType() {
        return new EntityObjectIntType();
    }

    /**
     * Create an instance of {@link BeginFunctionType }
     * 
     */
    public BeginFunctionType createBeginFunctionType() {
        return new BeginFunctionType();
    }

    /**
     * Create an instance of {@link RegexCaptureFunctionType }
     * 
     */
    public RegexCaptureFunctionType createRegexCaptureFunctionType() {
        return new RegexCaptureFunctionType();
    }

    /**
     * Create an instance of {@link EntityObjectBinaryType }
     * 
     */
    public EntityObjectBinaryType createEntityObjectBinaryType() {
        return new EntityObjectBinaryType();
    }

    /**
     * Create an instance of {@link EntityStateFileSetRevisionType }
     * 
     */
    public EntityStateFileSetRevisionType createEntityStateFileSetRevisionType() {
        return new EntityStateFileSetRevisionType();
    }

    /**
     * Create an instance of {@link EntityStateAnySimpleType }
     * 
     */
    public EntityStateAnySimpleType createEntityStateAnySimpleType() {
        return new EntityStateAnySimpleType();
    }

    /**
     * Create an instance of {@link EntityObjectIPAddressType }
     * 
     */
    public EntityObjectIPAddressType createEntityObjectIPAddressType() {
        return new EntityObjectIPAddressType();
    }

    /**
     * Create an instance of {@link EntityStateStringType }
     * 
     */
    public EntityStateStringType createEntityStateStringType() {
        return new EntityStateStringType();
    }

    /**
     * Create an instance of {@link LiteralComponentType }
     * 
     */
    public LiteralComponentType createLiteralComponentType() {
        return new LiteralComponentType();
    }

    /**
     * Create an instance of {@link EndFunctionType }
     * 
     */
    public EndFunctionType createEndFunctionType() {
        return new EndFunctionType();
    }

    /**
     * Create an instance of {@link TimeDifferenceFunctionType }
     * 
     */
    public TimeDifferenceFunctionType createTimeDifferenceFunctionType() {
        return new TimeDifferenceFunctionType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link ObjectComponentType }
     * 
     */
    public ObjectComponentType createObjectComponentType() {
        return new ObjectComponentType();
    }

    /**
     * Create an instance of {@link UniqueFunctionType }
     * 
     */
    public UniqueFunctionType createUniqueFunctionType() {
        return new UniqueFunctionType();
    }

    /**
     * Create an instance of {@link NotesType }
     * 
     */
    public NotesType createNotesType() {
        return new NotesType();
    }

    /**
     * Create an instance of {@link EntityStateBinaryType }
     * 
     */
    public EntityStateBinaryType createEntityStateBinaryType() {
        return new EntityStateBinaryType();
    }

    /**
     * Create an instance of {@link PossibleValueType }
     * 
     */
    public PossibleValueType createPossibleValueType() {
        return new PossibleValueType();
    }

    /**
     * Create an instance of {@link EntityObjectRecordType }
     * 
     */
    public EntityObjectRecordType createEntityObjectRecordType() {
        return new EntityObjectRecordType();
    }

    /**
     * Create an instance of {@link EntityStateEVRStringType }
     * 
     */
    public EntityStateEVRStringType createEntityStateEVRStringType() {
        return new EntityStateEVRStringType();
    }

    /**
     * Create an instance of {@link CountFunctionType }
     * 
     */
    public CountFunctionType createCountFunctionType() {
        return new CountFunctionType();
    }

    /**
     * Create an instance of {@link EntityStateRecordType }
     * 
     */
    public EntityStateRecordType createEntityStateRecordType() {
        return new EntityStateRecordType();
    }

    /**
     * Create an instance of {@link EntityStateBoolType }
     * 
     */
    public EntityStateBoolType createEntityStateBoolType() {
        return new EntityStateBoolType();
    }

    /**
     * Create an instance of {@link EntityStateIPAddressStringType }
     * 
     */
    public EntityStateIPAddressStringType createEntityStateIPAddressStringType() {
        return new EntityStateIPAddressStringType();
    }

    /**
     * Create an instance of {@link StateRefType }
     * 
     */
    public StateRefType createStateRefType() {
        return new StateRefType();
    }

    /**
     * Create an instance of {@link SubstringFunctionType }
     * 
     */
    public SubstringFunctionType createSubstringFunctionType() {
        return new SubstringFunctionType();
    }

    /**
     * Create an instance of {@link CriterionType }
     * 
     */
    public CriterionType createCriterionType() {
        return new CriterionType();
    }

    /**
     * Create an instance of {@link ObjectRefType }
     * 
     */
    public ObjectRefType createObjectRefType() {
        return new ObjectRefType();
    }

    /**
     * Create an instance of {@link ConcatFunctionType }
     * 
     */
    public ConcatFunctionType createConcatFunctionType() {
        return new ConcatFunctionType();
    }

    /**
     * Create an instance of {@link VariableComponentType }
     * 
     */
    public VariableComponentType createVariableComponentType() {
        return new VariableComponentType();
    }

    /**
     * Create an instance of {@link CriteriaType }
     * 
     */
    public CriteriaType createCriteriaType() {
        return new CriteriaType();
    }

    /**
     * Create an instance of {@link EntityObjectStringType }
     * 
     */
    public EntityObjectStringType createEntityObjectStringType() {
        return new EntityObjectStringType();
    }

    /**
     * Create an instance of {@link ExtendDefinitionType }
     * 
     */
    public ExtendDefinitionType createExtendDefinitionType() {
        return new ExtendDefinitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "state")
    public JAXBElement<StateType> createState(StateType value) {
        return new JAXBElement<StateType>(_State_QNAME, StateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefinitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "definition")
    public JAXBElement<DefinitionType> createDefinition(DefinitionType value) {
        return new JAXBElement<DefinitionType>(_Definition_QNAME, DefinitionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocalVariable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "local_variable", substitutionHeadNamespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", substitutionHeadName = "variable")
    public JAXBElement<LocalVariable> createLocalVariable(LocalVariable value) {
        return new JAXBElement<LocalVariable>(_LocalVariable_QNAME, LocalVariable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalVariable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "external_variable", substitutionHeadNamespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", substitutionHeadName = "variable")
    public JAXBElement<ExternalVariable> createExternalVariable(ExternalVariable value) {
        return new JAXBElement<ExternalVariable>(_ExternalVariable_QNAME, ExternalVariable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariableType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "variable")
    public JAXBElement<VariableType> createVariable(VariableType value) {
        return new JAXBElement<VariableType>(_Variable_QNAME, VariableType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "test")
    public JAXBElement<TestType> createTest(TestType value) {
        return new JAXBElement<TestType>(_Test_QNAME, TestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConstantVariable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", name = "constant_variable", substitutionHeadNamespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", substitutionHeadName = "variable")
    public JAXBElement<ConstantVariable> createConstantVariable(ConstantVariable value) {
        return new JAXBElement<ConstantVariable>(_ConstantVariable_QNAME, ConstantVariable.class, null, value);
    }

}
